spring.application.name=rag_backend
python.rag.service.url=${PYTHON_RAG_SERVICE_URL:http://13.49.138.96:8000/api/query}

spring.datasource.url=jdbc:h2:mem:ragdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true