spring.application.name=rag_backend
python.rag.service.url=${PYTHON_RAG_SERVICE_URL:http://13.49.138.96:8000}


spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.pgyoyemnywtqwouoreru
spring.datasource.password=${SUPA_BASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update